defaults: &defaults
  spotify_playlist_id: 694hppbaap4qfleJdaM3PQ
  spotify_user_id: diegobarna
  phone_number: "+34651763077"

development:
  <<: *defaults

production:
  <<: *defaults

test: &test
  <<: *defaults
